-- Supabase schema for SIA102x
-- Use this after you have enabled auth and created the "uploads" storage bucket.

-- 1) Application profile table that links to Supabase auth.users
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  role text not null default 'user' check (role in ('admin','employee','user')),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  approved_at timestamptz,
  approval_notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_profiles_username on public.profiles(username);

-- 2) Product grouping table
create table if not exists public.product_sets (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_product_sets_category on public.product_sets(category);

-- 3) Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  variant_name text,
  category text not null,
  image_path text,
  price numeric(18,2) not null default 0,
  actual_cost numeric(18,2) not null default 0,
  ordered_from_instagram int not null default 0,
  ordered_from_facebook int not null default 0,
  product_set_id bigint references public.product_sets(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_product_set_id on public.products(product_set_id);

-- 4) Product size summary table
create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  small int not null default 0,
  medium int not null default 0,
  large int not null default 0,
  total_small int not null default 0,
  total_medium int not null default 0,
  total_large int not null default 0,
  remaining_small int not null default 0,
  remaining_medium int not null default 0,
  remaining_large int not null default 0,
  small_fb int not null default 0,
  medium_fb int not null default 0,
  large_fb int not null default 0,
  small_ig int not null default 0,
  medium_ig int not null default 0,
  large_ig int not null default 0
);

create index if not exists idx_product_sizes_product_id on public.product_sizes(product_id);

-- 5) Size chart table
create table if not exists public.sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  quantity int not null default 0,
  total_quantity int not null default 0,
  remaining_quantity int not null default 0,
  facebook_quantity int not null default 0,
  instagram_quantity int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_sizes_product_id on public.sizes(product_id);

-- 6) Customers
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  total_orders int not null default 0,
  total_spent numeric(18,2) not null default 0,
  is_repeat_customer boolean not null default false,
  cancelled_order_count int not null default 0,
  first_order_date timestamptz not null default now(),
  last_order_date timestamptz not null default now(),
  manual_bogus boolean not null default false
);

create index if not exists idx_customers_name on public.customers(name);

-- 7) Orders
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text not null,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  quantity int not null default 0,
  platform text not null,
  unit_price numeric(18,2) not null default 0,
  profit_per_unit numeric(18,2) not null default 0,
  total_amount numeric(18,2) not null default 0,
  total_profit numeric(18,2) not null default 0,
  is_paid boolean not null default false,
  status text not null default 'Active' check (status in ('Active','Cancelled','Completed')),
  order_date timestamptz not null default now(),
  cancelled_date timestamptz,
  cancellation_reason text,
  contact_number text,
  address text,
  shipping_method text,
  payment_method text,
  shipping_fee numeric(18,2) not null default 0,
  employee_name text,
  transaction_id text
);

create index if not exists idx_orders_customer_id on public.orders(customer_id);
create index if not exists idx_orders_product_id on public.orders(product_id);

-- 8) Stock transactions
create table if not exists public.stock_transactions (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  quantity_added int not null default 0,
  date_added timestamptz not null default now(),
  note text,
  username text
);

create index if not exists idx_stock_transactions_product_id on public.stock_transactions(product_id);

-- 9) Expenses
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  name text not null,
  amount numeric(18,2) not null default 0,
  created_date timestamptz not null default now(),
  updated_date timestamptz,
  description text
);

-- RLS helper functions
create or replace function public.is_admin() returns boolean language sql stable as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  );
$$;

create or replace function public.is_admin_or_employee() returns boolean language sql stable as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'employee')
      and p.is_active = true
  );
$$;

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.product_sets enable row level security;
alter table public.products enable row level security;
alter table public.product_sizes enable row level security;
alter table public.sizes enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.stock_transactions enable row level security;
alter table public.expenses enable row level security;

-- Profiles policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'profiles'
      AND policyname = 'Profiles - select own'
  ) THEN
    CREATE POLICY "Profiles - select own"
      ON public.profiles
      FOR SELECT
      USING (auth.uid() = id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'profiles'
      AND policyname = 'Profiles - insert own'
  ) THEN
    CREATE POLICY "Profiles - insert own"
      ON public.profiles
      FOR INSERT
      WITH CHECK (auth.uid() = id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'profiles'
      AND policyname = 'Profiles - update own'
  ) THEN
    CREATE POLICY "Profiles - update own"
      ON public.profiles
      FOR UPDATE
      USING (auth.uid() = id)
      WITH CHECK (auth.uid() = id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'profiles'
      AND policyname = 'Profiles - admin manage'
  ) THEN
    CREATE POLICY "Profiles - admin manage"
      ON public.profiles
      FOR ALL
      USING (public.is_admin())
      WITH CHECK (public.is_admin());
  END IF;
END $$;

-- Catalog and data policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'product_sets'
      AND policyname = 'Allow authenticated select on public tables'
  ) THEN
    CREATE POLICY "Allow authenticated select on public tables"
      ON public.product_sets
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'product_sets'
      AND policyname = 'Admin/employee modify product_sets'
  ) THEN
    CREATE POLICY "Admin/employee modify product_sets"
      ON public.product_sets
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'products'
      AND policyname = 'Allow authenticated select on products'
  ) THEN
    CREATE POLICY "Allow authenticated select on products"
      ON public.products
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'products'
      AND policyname = 'Admin/employee modify products'
  ) THEN
    CREATE POLICY "Admin/employee modify products"
      ON public.products
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'product_sizes'
      AND policyname = 'Allow authenticated select on product_sizes'
  ) THEN
    CREATE POLICY "Allow authenticated select on product_sizes"
      ON public.product_sizes
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'product_sizes'
      AND policyname = 'Admin/employee modify product_sizes'
  ) THEN
    CREATE POLICY "Admin/employee modify product_sizes"
      ON public.product_sizes
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sizes'
      AND policyname = 'Allow authenticated select on sizes'
  ) THEN
    CREATE POLICY "Allow authenticated select on sizes"
      ON public.sizes
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'sizes'
      AND policyname = 'Admin/employee modify sizes'
  ) THEN
    CREATE POLICY "Admin/employee modify sizes"
      ON public.sizes
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'customers'
      AND policyname = 'Allow authenticated select on customers'
  ) THEN
    CREATE POLICY "Allow authenticated select on customers"
      ON public.customers
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'customers'
      AND policyname = 'Admin/employee modify customers'
  ) THEN
    CREATE POLICY "Admin/employee modify customers"
      ON public.customers
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'orders'
      AND policyname = 'Allow authenticated select on orders'
  ) THEN
    CREATE POLICY "Allow authenticated select on orders"
      ON public.orders
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'orders'
      AND policyname = 'Admin/employee modify orders'
  ) THEN
    CREATE POLICY "Admin/employee modify orders"
      ON public.orders
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stock_transactions'
      AND policyname = 'Allow authenticated select on stock_transactions'
  ) THEN
    CREATE POLICY "Allow authenticated select on stock_transactions"
      ON public.stock_transactions
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'stock_transactions'
      AND policyname = 'Admin/employee modify stock_transactions'
  ) THEN
    CREATE POLICY "Admin/employee modify stock_transactions"
      ON public.stock_transactions
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'expenses'
      AND policyname = 'Allow authenticated select on expenses'
  ) THEN
    CREATE POLICY "Allow authenticated select on expenses"
      ON public.expenses
      FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'expenses'
      AND policyname = 'Admin/employee modify expenses'
  ) THEN
    CREATE POLICY "Admin/employee modify expenses"
      ON public.expenses
      FOR ALL
      USING (public.is_admin_or_employee())
      WITH CHECK (public.is_admin_or_employee());
  END IF;
END $$;
